### PR TITLE
rpath is bad

### PR DESCRIPTION
**Pull request by protonesso**
https://wiki.debian.org/RpathIssue for more info.

### CODE REVIEW

**Comment by kittyhacker101** [comment]
RPATH is only enabled for development builds, and is disabled in all release builds. Therefore, this is not an issue for distributing binaries, and only a minor issue for developers (you can easily recompile your development build if the Rust standard library is updated).

Is there any real reason that RPATH should be disabled in development builds too?

**Comment by protonesso** [comment]
Why you're not disable rpath for development builds? Just, curious

**Comment by kittyhacker101** [comment]
It makes development builds a bit smaller. It's not a big difference, but development builds tend to be huge (more than 12x larger than release builds), so trying to save a bit of space could be a bit helpful for developers with limited storage space.

**Comment by protonesso** [comment]
kek

**Pull request closed without merging**
